name: DrugEscape CI/CD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  Build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Clean and Build Jar
      run: ./gradlew clean build

    - name: Build Docker image
      run: docker build -t ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPOSITORY}} .

    - name: Sign in Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Push Docker image
      run: docker push ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPOSITORY}}

  Deploy:
    name: Deploy application
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Execute remote SSH commands
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd ${{secrets.REMOTE_DOCKER_PATH}}
          docker compose down
          docker pull ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPOSITORY}}
          docker compose up -d
        host: ${{ secrets.REMOTE_HOST }}
        user: ${{ secrets.REMOTE_SSH_ID }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
